### ISSUE TITLE
Suggestion: allow for a way to share spoilers with other people

### ISSUE THREAD

**Issue by ETR-BTF** [amickael/spoilizer#15]
Make it so that when you upload a spoiler log you can share the URL with others (e.g. support staff and multiworld partners). Sharing URLs is easier than sharing files and it also saves others the effort of having to upload the log themselves.

**Comment by amickael** [comment]
I like this idea, however the current site operates 100% on the frontend, this would require an API on the backend and a database or some kind of other storage. I'd like to get the rest of the spoiler log working first, but afterward this would be pretty simple to set up.

**Comment by amickael** [comment]
Closed by #20
