### ISSUE TITLE
Suggestions: Increased Functionality 

### ISSUE THREAD

**Issue by DukeDragon28** [amickael/spoilizer#3]
I feel like there are 2 main things from logs that the program needs to be able to show. The first is the entrance list and the second is the settings used (such as what the item pool is, tricks in logic, what the bridge requirement is etc)

**Comment by ETR-BTF** [comment]
I would like to point out that this project could really shine if it finds a good way to exhibit the seed's entrances in the case of an entrance randomizer seed, because currently reading entrances is quite difficult.

**Comment by amickael** [comment]
Thanks @ETR-BTF, I created #2 to address this issue. You are much more familiar than I am, so please feel free to expand on what I've written (which isn't much).

**Comment by amickael** [comment]
Closing this issue, splitting into #2 and #12
